import { LeadStatus } from "@/types/lead";

export const leadStatuses: LeadStatus[] = [
  "Nouveau",
  "Apl en abs",
  "PI",
  "Reviendra vers nous",
  "En réflexion",
  "Souhaite être rappelé(e) plus tard",
  "À rappeler",
  "RDV pris",
  "RDV fixé",
  "RDV confirmé",
  "RDV programmé",
  "No show",
  "Client converti",
  "Acompte envoyé",
  "Acompte reçu",
  "Acompte validé",
  "Acompte en attente",
  "Devis",
  "Vendu",
  "Client",
  "Perdu",
  "Numéro invalide",
  "Prospect perdu",
  "Doublon",
  "Hors zone",
  "Message WhatsApp envoyé",
  "SMS envoyé",
  "Message vocal laissé",
  "Mail envoyé",
  "Mail/SMS Injoignable",
  "Msg vocal + Mail",
];

export const inactiveLeadStatuses: LeadStatus[] = [
  "Perdu",
  "Prospect perdu",
  "Numéro invalide",
  "Doublon",
  "Hors zone",
  "No show",
];

export const leadStatusClasses: Record<LeadStatus, string> = {
  Nouveau: "bg-blue-100 text-blue-700 ring-blue-200",
  "Apl en abs": "bg-cyan-100 text-cyan-800 ring-cyan-200",
  PI: "bg-red-700 text-white ring-red-700",
  "Reviendra vers nous": "bg-red-100 text-red-700 ring-red-200",
  "En réflexion": "bg-yellow-100 text-yellow-800 ring-yellow-200",
  "Souhaite être rappelé(e) plus tard":
    "bg-yellow-100 text-yellow-800 ring-yellow-200",
  "À rappeler": "bg-orange-100 text-orange-700 ring-orange-200",
  "RDV pris": "bg-green-100 text-green-700 ring-green-200",
  "RDV fixé": "bg-lime-100 text-lime-700 ring-lime-200",
  "RDV confirmé": "bg-emerald-100 text-emerald-700 ring-emerald-200",
  "RDV programmé": "bg-violet-100 text-violet-700 ring-violet-200",
  "No show": "bg-zinc-800 text-white ring-zinc-800",
  "Client converti": "bg-emerald-700 text-white ring-emerald-700",
  "Acompte envoyé": "bg-amber-100 text-amber-700 ring-amber-200",
  "Acompte reçu": "bg-emerald-100 text-emerald-700 ring-emerald-200",
  "Acompte validé": "bg-green-100 text-green-700 ring-green-200",
  "Acompte en attente": "bg-yellow-100 text-yellow-800 ring-yellow-200",
  Devis: "bg-cyan-100 text-cyan-700 ring-cyan-200",
  Vendu: "bg-lime-100 text-lime-700 ring-lime-200",
  Client: "bg-green-100 text-green-700 ring-green-200",
  Perdu: "bg-red-100 text-red-700 ring-red-200",
  "Numéro invalide": "bg-red-700 text-white ring-red-700",
  "Prospect perdu": "bg-red-700 text-white ring-red-700",
  Doublon: "bg-red-700 text-white ring-red-700",
  "Hors zone": "bg-red-700 text-white ring-red-700",
  "Message WhatsApp envoyé": "bg-zinc-100 text-zinc-800 ring-zinc-200",
  "SMS envoyé": "bg-zinc-100 text-zinc-800 ring-zinc-200",
  "Message vocal laissé": "bg-zinc-100 text-zinc-800 ring-zinc-200",
  "Mail envoyé": "bg-zinc-100 text-zinc-800 ring-zinc-200",
  "Mail/SMS Injoignable": "bg-zinc-100 text-zinc-800 ring-zinc-200",
  "Msg vocal + Mail": "bg-cyan-100 text-cyan-800 ring-cyan-200",
};
