import { Lead } from "@/types/lead";

export const leads: Lead[] = [
  {
    id: "1",
    firstName: "Marie",
    lastName: "Dubois",
    phone: "06 12 34 56 78",
    email: "marie@email.com",
    treatment: "Épilation Laser",
    source: "Facebook",
    campaign: "Laser juillet",
    status: "Nouveau",
    dealAmount: 0,
    commercial: "Samantha",
    createdAt: "Aujourd'hui 09:14",
    createdDate: "2026-07-25",
    nextAction: "Appeler à 17h",
    reminderDate: "2026-07-25",
    activityLog: [
      {
        id: "1-created",
        author: "Système",
        date: "Aujourd'hui 09:14",
        text: "Lead reçu via Facebook.",
        type: "system",
      },
    ],
  },
  {
    id: "2",
    firstName: "Julie",
    lastName: "Martin",
    phone: "06 22 33 44 55",
    email: "julie@email.com",
    treatment: "Cryolipolyse",
    source: "Google",
    campaign: "Cryo été",
    status: "À rappeler",
    dealAmount: 0,
    commercial: "Thomas",
    createdAt: "Hier",
    createdDate: "2026-07-24",
    nextAction: "WhatsApp",
    reminderDate: "2026-07-26",
    activityLog: [
      {
        id: "2-created",
        author: "Système",
        date: "Hier",
        text: "Lead reçu via Google.",
        type: "system",
      },
    ],
  },
  {
    id: "3",
    firstName: "Sarah",
    lastName: "Bernard",
    phone: "06 98 76 54 32",
    email: "sarah@email.com",
    treatment: "Hydrafacial",
    source: "Instagram",
    campaign: "Hydrafacial",
    status: "RDV programmé",
    dealAmount: 0,
    commercial: "Camille",
    createdAt: "22/07",
    createdDate: "2026-07-22",
    nextAction: "RDV lundi",
    reminderDate: "2026-07-28",
    activityLog: [
      {
        id: "3-created",
        author: "Système",
        date: "22/07",
        text: "Lead reçu via Instagram.",
        type: "system",
      },
    ],
  },
];
